name: nsmn
dependencies:
  - python=3.6   # or 2.7
  - pytorch=0.4.1
  - wget
  - pexpect
  - inflection
  - pip
  - pip:
    - fire
    - allennlp==0.7.1
    - sqlitedict
    - flashtext

    
    
    
    
    
    
    
    
    
